[graph]
features = ["posix-acl"]

[licenses]
version = 2
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "Unicode-3.0",
    "Zlib",
    "bzip2-1.0.6",
]
exceptions = [
    { crate = "acl-sys", allow = ["LGPL-2.1"] },
]


[licenses.private]
ignore = false

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]

[advisories]
version = 2