[build]
rustflags = []
[target.'cfg(has_aes)']
rustflags = ["-Ctarget-feature=+aes"]
[target.'cfg(has_sse2)']
rustflags = ["-Ctarget-feature=+sse2"]
[target.'cfg(has_ssse3)']
rustflags = ["-Ctarget-feature=+ssse3"]
[target.'cfg(has_sse4_1)']
rustflags = ["-Ctarget-feature=+sse4.1"]
[target.'cfg(has_neon)']
rustflags = ["-Ctarget-feature=+neon"]
[target.'cfg(has_sha2)']
rustflags = ["-Ctarget-feature=+sha2"]