name: Build and test workflow

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        include:
          - os: ubuntu-latest
            libacl: libacl1-dev
            pkg_config: pkg-config
            libudev: libudev-dev
            toolchain: stable
            target: x86_64-unknown-linux-gnu
            name: Linux (Ubuntu)
            fid: x86_64-linux
          - os: windows-latest
            libacl: ""
            toolchain: stable
            target: x86_64-pc-windows-msvc
            name: Windows x86_64 (MSVC)
          - os: macos-latest
            libacl: ""
            toolchain: stable
            target: aarch64-apple-darwin
            name: macOS (arm64)
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        target: ${{ matrix.target }}
        components: clippy
        default: true
    
    - name: Install deps (Linux only)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt update && sudo apt install -y ${{ matrix.libacl }} ${{ matrix.pkg_config }} ${{ matrix.libudev }}
    
    - name: Build ${{ matrix.target }}
      run: cargo clippy --verbose --all-features --target ${{ matrix.target }}
    
    - name: Run tests
      run: cargo test --verbose --all-features --target ${{ matrix.target }}
